import Header from "./Header/Header.jsx";
import Footer from "./Footer/Footer.jsx";
import Container from "./container/Container.jsx";
import Logo from "./Logo.jsx";
import LogOutBtn from "./Header/LogoOutBtn.jsx";
import SignUp from "./Signup.jsx";
import Login from "./Login.jsx";
// import { LogIn as LogInPage } from "../Pages/LogIn.jsx";
import Button from "./Button.jsx";
// import Post from "./Post.jsx";
import PostForm from "./post-form/PostForm.jsx";
import PostCard from "./PostCard.jsx";
import AuthLayout from "./AuthLayout.jsx";
import AllPosts from "../Pages/AllPosts.jsx";
import Home from "../Pages/Home.jsx";
import AddPost from "../Pages/AddPost.jsx";
import EditPost from "../Pages/EditPost.jsx";
import Input from "./Input.jsx";
import Post from "../Pages/Post.jsx";
import Select from "./Select.jsx";
export { Header, Footer, Container, Logo, Select, LogOutBtn, Input, SignUp, Login, Post, PostForm, PostCard, Button, AuthLayout, Home, AllPosts, AddPost, EditPost };
